[tasks.lint]
dependencies = ["clippy-flow"]

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.pre-ci-flow]
dependencies = ["deny", "lint"]